
CC=mpicc
CFLAGS= -O -Wall -std=c99 -g

#Sorry for the bad make file practices, but it does work 

ch3_3-12a: ch3_3-12a.c ch3_3-9
	$(CC) $(CFLAGS) -o $@ $< 

ch3_3-9: ch3_3-9.c
	$(CC) $(CFLAGS) -o $@ $< 


